### ISSUE TITLE
Declination should be in degrees, arcminutes and arcseconds

### ISSUE THREAD

**Issue by thatcatfromspace** [csymlstd/visible-planets-api#1]
Hello there! I've been using your API for a couple days now and it's great! One thing I noticed is that declination is also in hours, minutes and seconds while the units are totally different for declination, which are degrees, arcminutes and arcseconds. Please find a fix to it!
![image](https://user-images.githubusercontent.com/79753351/117027227-223b5200-ad1a-11eb-9982-d55b5d654fa3.png)

**Comment by csymlstd** [comment]
Hi! Glad you like the API. The units were simply misnamed and fixed in the new v2 endpoint!
